[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_url = "https://eth-sepolia.g.alchemy.com/v2/AwXNQB1sZceWq5qoYpeR7U0jsYYvoBHv"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@aave-v3-core/=lib/aave-v3-core/contracts/",
    "@aave-v3-periphery/=lib/aave-v3-periphery/contracts/"
]
